#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# config/routes.yaml

# the "app_banque" route name is not important yet
app_banque:
    path: /banque
    controller: App\Controller\BanqueController::number

    